### ISSUE TITLE
Email message could not be registered error

### ISSUE THREAD

**Issue by larsenv** [irdkwia/pelipper-test#6]
@irdkwia when I try to register email address I get aforementioned error

**Comment by irdkwia** [comment]
Sorry for the late reply
If you were trying with a proper email address, this isn't fully supported yet; the code is able to interact with the game's email feature, but this has currently been implemented with Discord accounts, not proper email addresses
Proper email support for registering could be added here: https://github.com/irdkwia/pelipper-test/blob/99974ea96344f709f1fb3a67383591a682bd1fa2/handlers/httphandler.py#L342-L363
The code can already tell apart email from discord accounts, what needs to be done is actually send an email containing the code to the received address
However, note that email support is something that is entirely done server side, as the game client only provides email input from the client, actual logic of sending messages is done server side, which has to be implemented in proper places
Also, while proper email support is welcome, I do not see it as important because every other feature can be used without it and European versions of the game do not even have this feature available
